# Docker Compose Configuration
# visit https://docs.docker.com/compose/

services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_URI=${DATABASE_URI}
    ports:
      - '4000:4000'
    depends_on:
      - database
    env_file:
      - .env

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
    # env_file:
    #   - .env